virustotal_api_key: "YOUR_VIRUSTOTAL_API_KEY"
alienvault_api_key: "YOUR_ALIENVAULT_API_KEY"
concurrency: 5
user_agents:
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)"
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko)"
  - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)"
rate_limit: 60
